In [39]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [121]:
numerical = pd.read_csv("/Users/giacomorossini/Desktop/IRONHACK/Class/14_week/numerical.csv")
target = pd.read_csv("/Users/giacomorossini/Desktop/IRONHACK/Class/14_week/target.csv")
targetB = target['TARGET_B']
targetD = target['TARGET_D']

In [41]:
'''
You are revisiting the Healthcare for All Case Study. 
You are provided with this historical data about Donors and how much they donated. 
Your task is to build a machine learning model that will help the company identify people who are more likely 
to donate and then try to predict the donation amount.
'''

'\nYou are revisiting the Healthcare for All Case Study. \nYou are provided with this historical data about Donors and how much they donated. \nYour task is to build a machine learning model that will help the company identify people who are more likely \nto donate and then try to predict the donation amount.\n'

In [111]:
# Check the datatypes of all the columns in the data. 
len(numerical.columns) #315
numerical.dtypes

TCODE         int64
AGE         float64
INCOME        int64
WEALTH1       int64
HIT           int64
             ...   
AVGGIFT     float64
CONTROLN      int64
HPHONE_D      int64
RFA_2F        int64
CLUSTER2      int64
Length: 315, dtype: object

In [112]:
data = pd.DataFrame(numerical.isna().sum()/len(numerical)).reset_index()
data.columns=['columns_name', 'nulls_percentage']
data.sort_values(by='nulls_percentage', ascending=False)

columns_name  nulls_percentage
0          TCODE               0.0
207         EIC4               0.0
214        EIC11               0.0
213        EIC10               0.0
212         EIC9               0.0
..           ...               ...
104        ETHC1               0.0
103        HHD12               0.0
102        HHD11               0.0
101        HHD10               0.0
314     CLUSTER2               0.0

[315 rows x 2 columns]

In [114]:
treshold = 0.10
data_wran=data[data['nulls_percentage']>treshold]
drop_col = list(data_wran['columns_name'])
numerical = numerical.drop(drop_col, axis = 1)

In [115]:
data1 = pd.DataFrame(numerical.isna().sum()).reset_index()
data1.columns=['columns_name', 'nulls_percentage']
col_nul = list(data1[data1['nulls_percentage'] != 0]['columns_name']) #len 11 cols
col_nul

[]

In [47]:
#for i in col_nul:
#    donors[i].fillna(max(set(list(donors[i])), key=list(donors[i]).count), inplace = True)

In [48]:
# laternative way to calculate the mode

#mode_values= donors.mode().iloc[0]
#donors = donors.fillna(mode_values)

In [118]:
#numerical = donors.select_dtypes(include = np.number)
categorical = numerical.select_dtypes(exclude = np.number)
categorical #no categorical

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[95412 rows x 0 columns]

In [165]:
# Split the data into a training set and a test set.

from sklearn.model_selection import train_test_split

Y = targetB
X = numerical

X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 42, test_size= 0.2)

In [166]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(X_train,y_train)
result = LR.score(X_test,y_test) 
print("The accuracy of the model is = ", round(result,2))

The accuracy of the model is =  0.95


In [137]:
from sklearn.metrics import precision_score #precision metrics
from sklearn.metrics import recall_score #recall metrics
from sklearn.metrics import f1_score #f1 metrics
from sklearn.metrics import classification_report #classification metrics

#maximizing recall for all healthy issue topic

pred = LR.predict(X_test)

print("Precision is : ", precision_score(y_test, pred))
print("Recall is : ", recall_score(y_test, pred))
print("F1 is : ", f1_score(y_test, pred))

print(classification_report(y_test, pred))

Precision is :  0.047619047619047616
Recall is :  0.0010224948875255625
F1 is :  0.002002002002002002
              precision    recall  f1-score   support

           0       0.95      1.00      0.97     18105
           1       0.05      0.00      0.00       978

    accuracy                           0.95     19083
   macro avg       0.50      0.50      0.49     19083
weighted avg       0.90      0.95      0.92     19083



In [139]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, pred)

array([[18085,    20],
       [  977,     1]])

In [ ]:
'''
Managing imbalance in the dataset

- Check for the imbalance.
- Use the resampling strategies used in class for upsampling and downsampling to create a balance between the two classes.
- Each time fit the model and see how the accuracy of the model has changed.

'''

In [143]:
print(target['TARGET_B'].value_counts())
data = pd.concat([numerical, target], axis=1)
#take out the other target not usefull to undersample/oversample
data=data.drop('TARGET_D', axis=1)

0    90569
1     4843
Name: TARGET_B, dtype: int64


# UNDERSAMPLE

In [148]:
category_0 = data[data['TARGET_B'] == 0]
category_1 = data[data['TARGET_B'] == 1]

In [149]:
category_0 = category_0.sample(len(category_1))

TCODE        AGE  INCOME  WEALTH1  HIT  MALEMILI  MALEVET  VIETVETS  \
66635      0  40.000000       5        9    0         5       31        51   
42851      0  63.000000       4        7   16         2       27        39   
47145      0  52.000000       4        9   12         8       49        38   
27439      1  72.000000       4        2    0         0       37        30   
73246      1  76.000000       4        9    0         0       16        17   
...      ...        ...     ...      ...  ...       ...      ...       ...   
35937      2  88.000000       6        9    0         0       27        13   
40701      0  79.000000       5        9    0         0       30        34   
1119       0  61.611649       5        9    0         0       42         8   
75182      0  70.000000       4        9    0         0       35        31   
52960      1  76.000000       5        9    0         0       29        38   

       WWIIVETS  LOCALGOV  ...  MINRAMNT  MAXRAMNT  LASTGIFT  TIMELAG  \
66635        17         7  ...       3.0      13.0      11.0       12   
42851        25        10  ...       3.0      16.0      16.0        6   
47145        18        11  ...       2.0       5.0       3.0       14   
27439        41         9  ...      10.0      19.0      19.0       16   
73246        43         3  ...       5.0      15.0      15.0       12   
...         ...       ...  ...       ...       ...       ...      ...   
35937        25         8  ...       2.0      10.0      10.0        7   
40701        10         6  ...       5.0      15.0      15.0        4   
1119         75        11  ...       5.0      15.0      15.0        4   
75182        39         5  ...       0.0      35.0      35.0       42   
52960        42         3  ...       5.0      15.0      15.0        6   

         AVGGIFT  CONTROLN  HPHONE_D  RFA_2F  CLUSTER2  TARGET_B  
66635   9.375000     27925         1       3        14         0  
42851   8.500000    105974         1       2        22         0  
47145   3.600000     33314         1       4        32         0  
27439  14.500000     80985         0       1        43         0  
73246  10.000000    144061         0       1        10         0  
...          ...       ...       ...     ...       ...       ...  
35937   6.105263     82058         0       3        14         0  
40701  12.407407      7263         0       1        21         0  
1119    8.500000     45323         0       1        32         0  
75182  21.000000      9955         1       2        54         0  
52960  10.500000    162393         0       1         2         0  

[4843 rows x 316 columns]

In [146]:
data = pd.concat([category_0, category_1], axis=0)
data['TARGET_B'].value_counts()

0    4843
1    4843
Name: TARGET_B, dtype: int64

In [151]:
Y = data['TARGET_B']
X = data.drop('TARGET_B', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 42, test_size= 0.2)

In [152]:
LR = LogisticRegression()
LR.fit(X_train,y_train)
LR.score(X_test,y_test) 

0.5500515995872033

In [153]:
pred = LR.predict(X_test)

print("Precision is : ", precision_score(y_test, pred))
print("Recall is : ", recall_score(y_test, pred))
print("F1 is : ", f1_score(y_test, pred))

print(classification_report(y_test, pred))

Precision is :  0.5414534288638689
Recall is :  0.5550891920251836
F1 is :  0.5481865284974092
              precision    recall  f1-score   support

           0       0.56      0.55      0.55       985
           1       0.54      0.56      0.55       953

    accuracy                           0.55      1938
   macro avg       0.55      0.55      0.55      1938
weighted avg       0.55      0.55      0.55      1938



In [154]:
confusion_matrix(y_test, pred)

array([[537, 448],
       [424, 529]])

# UPSAMPLE

In [157]:
data = pd.concat([numerical, target], axis=1)
#take out the other target not usefull to undersample/oversample
data=data.drop('TARGET_D', axis=1)

category_0 = data[data['TARGET_B'] == 0]
category_1 = data[data['TARGET_B'] == 1]

In [158]:
from sklearn.utils import resample
category_1 = resample(category_1, #data we are duplicating
                     replace = True, #replace the data by adding
                     n_samples = len(category_0), #number of samples
                     random_state= 42 
                     )

In [159]:
data = pd.concat([category_0, category_1], axis=0)
data['TARGET_B'].value_counts()

0    90569
1    90569
Name: TARGET_B, dtype: int64

In [160]:
Y = data['TARGET_B']
X = data.drop('TARGET_B', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state = 42, test_size= 0.2)

In [161]:
LR = LogisticRegression()
LR.fit(X_train,y_train)
LR.score(X_test,y_test) 

0.5396378491774318

In [162]:
pred = LR.predict(X_test)

print("Precision is : ", precision_score(y_test, pred))
print("Recall is : ", recall_score(y_test, pred))
print("F1 is : ", f1_score(y_test, pred))

print(classification_report(y_test, pred))

Precision is :  0.5459755947245162
Recall is :  0.4875619152449092
F1 is :  0.5151180369810444
              precision    recall  f1-score   support

           0       0.53      0.59      0.56     18058
           1       0.55      0.49      0.52     18170

    accuracy                           0.54     36228
   macro avg       0.54      0.54      0.54     36228
weighted avg       0.54      0.54      0.54     36228



In [163]:
confusion_matrix(y_test, pred)

array([[10691,  7367],
       [ 9311,  8859]])